### ISSUE TITLE
Contributing articles and tools

### ISSUE THREAD

**Issue by bemosior** [jgmize/wardley-maps#1]
Hello! I have [a list here](https://hiredthought.com/wardley-mapping/) containing various WM tools, articles, and other resources. Would you like me to put together a PR to add them to your list as well?

**Comment by jgmize** [comment]
Hi @bemosior, I created this repo just to take some notes and perhaps create some maps of my own in it. That's a nice list and I have no objections to PRs if you still want to file one, or if not I'll probably add a link myself later :)
